#baseURL: http://example.org/
#languageCode: en-us
#title: My New Hugo Site
#theme: Universal
#publishDir: docs                              # Output folder
#enableEmoji: true

baseURL: /                  # Hosting location.
languageCode: en-us                           # Locale
title: Acme Corporation                       # Name of the website
theme: Eclectic                               # Name of the theme
publishDir: docs                              # Output folder
enableEmoji: true                             # Enable Emoticons
enableInlineShortcodes: true
sectionPagesMenu: home
